package InterfazVisual;

/**
 *
 * @author FRAID
 */
public class CalculadoraBobina extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraBobina
     */
    public CalculadoraBobina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CalcularBTN = new javax.swing.JButton();
        LimpiarBTN = new javax.swing.JButton();
        RegresarBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TipoDeCable = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PesoCompleto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PesoActual = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        MarcaInicio = new javax.swing.JTextField();
        lbl = new javax.swing.JLabel();
        MarcaFin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Resultados = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CalcularBTN.setText("Calcular");
        CalcularBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularBTNActionPerformed(evt);
            }
        });
        getContentPane().add(CalcularBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));

        LimpiarBTN.setText("Limpiar");
        LimpiarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarBTNActionPerformed(evt);
            }
        });
        getContentPane().add(LimpiarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        RegresarBTN.setText("Regresar");
        RegresarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarBTNActionPerformed(evt);
            }
        });
        getContentPane().add(RegresarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, -1, -1));

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 1, 36)); // NOI18N
        jLabel1.setText("Calculadora Bobina");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 310, 40));

        TipoDeCable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UTP Cat 5e (Cobre)", "UTP Cat 6 (Cobre)", "UTP Cat 6A (Blindado)", "Fibra Óptica Monomodo (2 hilos)", "Fibra Óptica Multimodo (Armada)", "Coaxial RG-6" }));

        jLabel2.setText("Tipo Cable:");

        jLabel3.setText("Peso Completo (kg):");

        PesoCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesoCompletoActionPerformed(evt);
            }
        });

        jLabel4.setText("Peso Actual (kg):");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TipoDeCable, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PesoCompleto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PesoActual, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoDeCable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PesoCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(PesoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 190));

        jLabel5.setText("Marca Inicial:");

        lbl.setText("Marca Final:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MarcaFin, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(MarcaInicio))
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(MarcaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl)
                    .addComponent(MarcaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 290, 150));

        jLabel6.setText("Resultados:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        Resultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadosActionPerformed(evt);
            }
        });
        getContentPane().add(Resultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 310, 240, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PesoCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesoCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesoCompletoActionPerformed

    private void ResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadosActionPerformed

    private void CalcularBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularBTNActionPerformed
    try {
        double pesoMetro = 0;
        String seleccion = TipoDeCable.getSelectedItem().toString();

        switch (seleccion) {
            case "UTP Cat 5e (Cobre)": pesoMetro = 0.030; break;
            case "UTP Cat 6 (Cobre)": pesoMetro = 0.038; break;
            case "UTP Cat 6A (Blindado)": pesoMetro = 0.045; break;
            case "Fibra Óptica Monomodo (2 hilos)": pesoMetro = 0.020; break;
            case "Fibra Óptica Multimodo (Armada)": pesoMetro = 0.055; break;
            case "Coaxial RG-6": pesoMetro = 0.042; break;
            default: pesoMetro = 0.035;
        }

        String mensajeFinal = "";

        if (!PesoCompleto.getText().isEmpty() && !PesoActual.getText().isEmpty()) {
            double pCompleto = Double.parseDouble(PesoCompleto.getText());
            double pActual = Double.parseDouble(PesoActual.getText());
            
            double pesoNetoCableActual = pActual - 1.0; 
            double metrosRestantes = pesoNetoCableActual / pesoMetro;
            
            mensajeFinal = String.format("Restan aproximadamente: %.2f m", metrosRestantes);
        } 
        
        else if (!MarcaInicio.getText().isEmpty() && !MarcaFin.getText().isEmpty()) {
            double mInicio = Double.parseDouble(MarcaInicio.getText());
            double mFin = Double.parseDouble(MarcaFin.getText());
            
            double metrosEnBobina = Math.abs(mFin - mInicio);
            mensajeFinal = String.format("Longitud en tramo: %.2f m", metrosEnBobina);
        } 
        else {
            mensajeFinal = "Llene datos de Peso O Marcas";
        }

        Resultados.setText(mensajeFinal);

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingrese solo números");
    }
    }//GEN-LAST:event_CalcularBTNActionPerformed

    private void LimpiarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarBTNActionPerformed
    PesoCompleto.setText("");
    PesoActual.setText("");
    MarcaInicio.setText("");
    MarcaFin.setText("");
    Resultados.setText("");
    TipoDeCable.setSelectedIndex(0);
    }//GEN-LAST:event_LimpiarBTNActionPerformed

    private void RegresarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarBTNActionPerformed
    new PanelOpcionesTecnico().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_RegresarBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBobina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBobina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBobina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBobina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraBobina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcularBTN;
    private javax.swing.JButton LimpiarBTN;
    private javax.swing.JTextField MarcaFin;
    private javax.swing.JTextField MarcaInicio;
    private javax.swing.JTextField PesoActual;
    private javax.swing.JTextField PesoCompleto;
    private javax.swing.JButton RegresarBTN;
    private javax.swing.JTextField Resultados;
    private javax.swing.JComboBox<String> TipoDeCable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl;
    // End of variables declaration//GEN-END:variables
}
