/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazVisual;
import javax.swing.JOptionPane;   
import javax.swing.table.DefaultTableModel; 
import CapaDatos.ConexionDB;
import java.sql.Statement;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JTable;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;

/**
 *
 * @author FRAID
 */
public class PantallaSupervision extends javax.swing.JFrame {
 CapaDatos.ConexionDB db = new CapaDatos.ConexionDB();
    /**
     * Creates new form PantallaSupervision
     */
    public PantallaSupervision() {
        initComponents();
        this.setLocationRelativeTo(null);
        ActualizarBTNActionPerformed(null);
        ActualizaBTNActionPerformed(null);
    }

    public class MultiLineCellRenderer extends DefaultTableCellRenderer {
    @Override
  public Component getTableCellRendererComponent(JTable table, Object value, 
            boolean isSelected, boolean hasFocus, int row, int column) {
        
        // El secreto es usar etiquetas <html> y establecer un ancho para el cuerpo
        String text = "<html><body style='width: 350px; padding: 5px;'>" 
                    + (value != null ? value.toString() : "") 
                    + "</body></html>";
        
        return super.getTableCellRendererComponent(table, text, isSelected, hasFocus, row, column);
    }
}
    
    private void formatearTablaFallas() {
    // 1. Aplicar el renderizador multilínea a la columna Asunto (índice 2)
    Fallas.getColumnModel().getColumn(2).setCellRenderer(new MultiLineCellRenderer());
    
    // 2. Definir la altura de las filas (fija para todas)
    Fallas.setRowHeight(85);
    
    // 3. Fijar los anchos de las columnas para que no se muevan
    Fallas.getColumnModel().getColumn(0).setPreferredWidth(60);  // ID Ticket
    Fallas.getColumnModel().getColumn(1).setPreferredWidth(80);  // ID Proyecto
    Fallas.getColumnModel().getColumn(2).setPreferredWidth(500); // Asunto (Ancho predominante)
    Fallas.getColumnModel().getColumn(3).setPreferredWidth(90);  // Prioridad
    Fallas.getColumnModel().getColumn(4).setPreferredWidth(90);  // Estado
    Fallas.getColumnModel().getColumn(5).setPreferredWidth(150); // Fecha
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PanelControl = new javax.swing.JTabbedPane();
        ReporteFalla = new javax.swing.JScrollPane();
        ReporteFallas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Fallas = new javax.swing.JTable();
        ActualizarBTN = new javax.swing.JButton();
        ResolverBTN = new javax.swing.JButton();
        RevisionGabinete = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Gabinete = new javax.swing.JTable();
        ActualizaBTN = new javax.swing.JButton();
        RegresarBTN = new javax.swing.JButton();
        Export = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 1, 36)); // NOI18N
        jLabel1.setText("Panel de Control y Supervisión");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 450, 40));

        Fallas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Ticket", "ID Proyecto", "Asunto", "Prioridad", "Estado", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(Fallas);

        ActualizarBTN.setText("Actualizar");
        ActualizarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBTNActionPerformed(evt);
            }
        });

        ResolverBTN.setText("Resolver");
        ResolverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResolverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReporteFallasLayout = new javax.swing.GroupLayout(ReporteFallas);
        ReporteFallas.setLayout(ReporteFallasLayout);
        ReporteFallasLayout.setHorizontalGroup(
            ReporteFallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReporteFallasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(ReporteFallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ResolverBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActualizarBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        ReporteFallasLayout.setVerticalGroup(
            ReporteFallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReporteFallasLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(ActualizarBTN)
                .addGap(75, 75, 75)
                .addComponent(ResolverBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ReporteFallasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
        );

        ReporteFalla.setViewportView(ReporteFallas);

        PanelControl.addTab("Reporte de Fallas", ReporteFalla);

        Gabinete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Proyecto", "Limpieza", "Ventilación", "Cerradura", "Fecha revisión"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Gabinete);

        ActualizaBTN.setText("Actualizar");
        ActualizaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizaBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RevisionGabineteLayout = new javax.swing.GroupLayout(RevisionGabinete);
        RevisionGabinete.setLayout(RevisionGabineteLayout);
        RevisionGabineteLayout.setHorizontalGroup(
            RevisionGabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RevisionGabineteLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(ActualizaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        RevisionGabineteLayout.setVerticalGroup(
            RevisionGabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RevisionGabineteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ActualizaBTN)
                .addGap(181, 181, 181))
        );

        PanelControl.addTab("Revision Gabinete", RevisionGabinete);

        getContentPane().add(PanelControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1270, 470));

        RegresarBTN.setText("Regresar");
        RegresarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarBTNActionPerformed(evt);
            }
        });
        getContentPane().add(RegresarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 570, 110, -1));

        Export.setText("Exportar PDF");
        Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportActionPerformed(evt);
            }
        });
        getContentPane().add(Export, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBTNActionPerformed
    Fallas.setModel(db.obtenerTablaFallas());
    Fallas.setModel(db.obtenerTablaFallas());
    
    // 2. Aplicar el ajuste de línea a la columna de "Asunto" (Índice 2)
    Fallas.getColumnModel().getColumn(2).setCellRenderer(new MultiLineCellRenderer());
    
    // 3. Aumentar el alto de las filas para que el texto sea visible
    Fallas.setRowHeight(80); // Puedes ajustar este número según necesites más espacio
    
    // 4. (Opcional) Ajustar anchos para que se vea igual a tu imagen
    Fallas.getColumnModel().getColumn(0).setPreferredWidth(60);  // ID Ticket
    Fallas.getColumnModel().getColumn(1).setPreferredWidth(80);  // ID Proyecto
    Fallas.getColumnModel().getColumn(2).setPreferredWidth(450); // Asunto
    
    formatearTablaFallas();
    }//GEN-LAST:event_ActualizarBTNActionPerformed

    private void ActualizaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizaBTNActionPerformed
   DefaultTableModel modelo = (DefaultTableModel) Gabinete.getModel();
modelo.setRowCount(0);

try {
    // 1. Conexión a la base de datos
    java.sql.Connection cn = CapaDatos.ConexionDB.conectar(); 

    /* 2. Consulta SQL con filtrado de duplicados:
       Seleccionamos el ID y los valores correspondientes a la FECHA MÁXIMA (la más reciente) 
       agrupando por id_proyecto.
    */
    String sql = "SELECT t1.* FROM checklist_gabinete t1 " +
                 "INNER JOIN (SELECT id_proyecto, MAX(fecha_revision) as ultima_fecha " +
                 "FROM checklist_gabinete GROUP BY id_proyecto) t2 " +
                 "ON t1.id_proyecto = t2.id_proyecto AND t1.fecha_revision = t2.ultima_fecha";

    java.sql.PreparedStatement ps = cn.prepareStatement(sql);
    java.sql.ResultSet rs = ps.executeQuery();

    // 3. Llenado del modelo de la tabla
    while (rs.next()) {
        modelo.addRow(new Object[]{
            rs.getInt("id_proyecto"),
            rs.getString("limpieza"),
            rs.getString("ventilacion"),
            rs.getString("cerradura"),
            rs.getTimestamp("fecha_revision")
        });
    }

    // 4. Cierre de recursos
    rs.close();
    ps.close();
    cn.close();

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar revisiones: " + e.getMessage());
}
    }//GEN-LAST:event_ActualizaBTNActionPerformed

    
    
    private void ResolverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResolverBTNActionPerformed
 // 1. Obtener la fila seleccionada de la tabla visual
int filaSeleccionada = Fallas.getSelectedRow();

// 2. Validar selección
if (filaSeleccionada == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un ticket de la tabla para resolver.");
    return;
}

// 3. Confirmación de seguridad
int confirmar = javax.swing.JOptionPane.showConfirmDialog(this, 
    "¿Está seguro de marcar este ticket como resuelto? Se eliminará de la base de datos.", 
    "Confirmar Resolución", javax.swing.JOptionPane.YES_NO_OPTION);

if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
    try {
        // 4. Obtener el ID del Ticket (Columna 0 de la tabla visual)
        String idTicket = Fallas.getValueAt(filaSeleccionada, 0).toString();

        // 5. Conexión y depuración en la base de datos
        java.sql.Connection cn = CapaDatos.ConexionDB.conectar(); 
        
        // IMPORTANTE: Se cambia a la tabla 'tickets' y la columna 'id_ticket' 
        // según la estructura visual de tu Panel de Control
        java.sql.PreparedStatement ps = cn.prepareStatement("DELETE FROM tickets WHERE id_ticket = ?");
        ps.setString(1, idTicket);
        
        int resultado = ps.executeUpdate();

        if (resultado > 0) {
            // 6. Eliminar la fila de la tabla en la interfaz (GUI) inmediatamente
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) Fallas.getModel();
            modelo.removeRow(filaSeleccionada);
            
            javax.swing.JOptionPane.showMessageDialog(this, "¡Ticket resuelto y eliminado del sistema!");
        }
        
        cn.close();
        
    } catch (Exception e) {
        // Manejo de error si la tabla 'tickets' o la columna no existen
        javax.swing.JOptionPane.showMessageDialog(this, "Error al depurar base de datos: " + e.getMessage());
    }
}
    }//GEN-LAST:event_ResolverBTNActionPerformed

    private void ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportActionPerformed
    Document documento = new Document();
    try {
        String ruta = "Reporte_Supervision_Completo.pdf";
        PdfWriter.getInstance(documento, new FileOutputStream(ruta));
        documento.open();

        documento.add(new Paragraph("RESUMEN DE SUPERVISIÓN - SIMULADOR DE REDES"));
        documento.add(new Paragraph("=========================================="));
        documento.add(new Paragraph(" ")); 
        
        documento.add(new Paragraph("1. REPORTE DE FALLAS (TICKETS)"));
        documento.add(new Paragraph("Tickets totales: " + Fallas.getRowCount()));
        documento.add(new Paragraph(" "));

        PdfPTable tablaFallas = new PdfPTable(Fallas.getColumnCount());
       
        for (int i = 0; i < Fallas.getColumnCount(); i++) {
            tablaFallas.addCell(Fallas.getColumnName(i));
        }
        
        for (int rows = 0; rows < Fallas.getRowCount(); rows++) {
            for (int cols = 0; cols < Fallas.getColumnCount(); cols++) {
                tablaFallas.addCell(Fallas.getModel().getValueAt(rows, cols).toString());
            }
        }
        documento.add(tablaFallas);
        documento.add(new Paragraph(" "));

        documento.add(new Paragraph("2. REVISIONES DE GABINETE"));
        documento.add(new Paragraph("Revisiones totales: " + Gabinete.getRowCount()));
        documento.add(new Paragraph(" "));

        PdfPTable tablaGabinete = new PdfPTable(Gabinete.getColumnCount());

        for (int i = 0; i < Gabinete.getColumnCount(); i++) {
            tablaGabinete.addCell(Gabinete.getColumnName(i));
        }

        for (int rows = 0; rows < Gabinete.getRowCount(); rows++) {
            for (int cols = 0; cols < Gabinete.getColumnCount(); cols++) {
                tablaGabinete.addCell(Gabinete.getModel().getValueAt(rows, cols).toString());
            }
        }
        documento.add(tablaGabinete);

        documento.close();
        javax.swing.JOptionPane.showMessageDialog(this, "Reporte exportado con éxito a: " + ruta);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al generar PDF: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_ExportActionPerformed

    private void RegresarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarBTNActionPerformed
    new PanelOpcionesTecnico().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegresarBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaSupervision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaSupervision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaSupervision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaSupervision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaSupervision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizaBTN;
    private javax.swing.JButton ActualizarBTN;
    private javax.swing.JButton Export;
    private javax.swing.JTable Fallas;
    private javax.swing.JTable Gabinete;
    private javax.swing.JTabbedPane PanelControl;
    private javax.swing.JButton RegresarBTN;
    private javax.swing.JScrollPane ReporteFalla;
    private javax.swing.JPanel ReporteFallas;
    private javax.swing.JButton ResolverBTN;
    private javax.swing.JPanel RevisionGabinete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
